name: Deploy Backend to Azure
on:
  push:
    branches:
      - main
    paths:
      - "deploy/backend/**"
      - "modules/**"

  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      working_directory: "./deploy/backend"
    secrets: inherit
