name: Build and Push APBS Docker Image
on:
  push:
    branches:
      - main
    paths:
      - "container-apps/apbs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_BACKEND_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Image
        run: |
          docker build -t ${{ secrets.ACR_URL }}/apbs-azure:latest container-apps/apbs

      - name: Push Image
        run: |
          docker push ${{ secrets.ACR_URL }}/apbs-azure:latest
