name: Deploy to Azure
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_BACKEND_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu init
        id: init
        run: tofu init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: OpenTofu validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu plan
        run: tofu plan -no-color
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: OpenTofu apply
        run: tofu apply -no-color -auto-approve
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
