name: Reusable Azure Deployment Workflow
on:
  workflow_call:
    inputs:
      working_directory:
        required: true # The working directory to run the workflow in
        type: string
      workspace:
        required: false # The workspace to use for the workflow
        type: string
        default: default

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          tenant-id: ${{ secrets.TF_BACKEND_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: opentofu/setup-opentofu@v1

      - name: Set OpenTofu workspace
        run: tofu workspace select ${{ inputs.workspace }}

      - name: OpenTofu init
        id: init
        run: tofu init
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_acr_name: ${{ secrets.ACR_NAME }}
          TF_VAR_acr_resource_group_name: ${{ secrets.ACR_RESOURCE_GROUP_NAME }}
          GH_TOKEN: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

      - name: OpenTofu validate
        id: validate
        run: tofu validate -no-color

      - name: OpenTofu plan
        run: tofu plan -no-color > tofu-plan-${{ github.run_id }}.txt 2>&1
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_acr_name: ${{ secrets.ACR_NAME }}
          TF_VAR_acr_resource_group_name: ${{ secrets.ACR_RESOURCE_GROUP_NAME }}
          GH_TOKEN: ${{ secrets.TF_VAR_GITHUB_TOKEN }}

      - name: OpenTofu apply
        run: tofu apply -no-color -auto-approve
        env:
          ARM_USE_OIDC: true
          ARM_CLIENT_ID: ${{ secrets.TF_BACKEND_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.TF_BACKEND_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          TF_VAR_acr_name: ${{ secrets.ACR_NAME }}
          TF_VAR_acr_resource_group_name: ${{ secrets.ACR_RESOURCE_GROUP_NAME }}
          GH_TOKEN: ${{ secrets.TF_VAR_GITHUB_TOKEN }}
